server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/test
    username: user
    password: 1234
    hikari:
      schema: public
